# -*- coding: utf-8 -*-
"""Scrapy pipline item classes.

This module provides structured data items used in crawling processes. There
are two categories:
    (1) scrapy.Item. These classes are generated by scrapy spiders and handled
by scrapy pipelines. The classes contains most fields of corresponding database
table, but not necessary same as database table.
    (2) self defined namedtuple. These classes are used to store data selected
from database and then used as input for scrapy spiders. Often they only
contains only a small part and neccessary fields of the corresponding
database table.
"""
#
# written by Chengcheng Shao <sccotte@gmail.com>

from collections import namedtuple

import scrapy


class UrlItem(scrapy.Item):
    """Url entry, see Url table model."""
    id = scrapy.Field()
    raw = scrapy.Field()
    expanded = scrapy.Field()
    canonical = scrapy.Field()
    created_at = scrapy.Field()
    date_published = scrapy.Field()
    article_id = scrapy.Field()
    site_id = scrapy.Field()
    status_code = scrapy.Field()
    # html is a temperate field, not in the database table.
    # before inserting into table, it would be popped out and copied to article
    html = scrapy.Field()


class ArticleItem(scrapy.Item):
    """Article entry, see Article table model."""
    id = scrapy.Field()
    canonical_url = scrapy.Field()
    site_id = scrapy.Field()
    group_id = scrapy.Field()
    title = scrapy.Field()
    content = scrapy.Field()
    meta = scrapy.Field()
    date_published = scrapy.Field()
    date_captured = scrapy.Field()
    status_code = scrapy.Field()
    # copied from urlitem
    html = scrapy.Field()


class NTUrl(namedtuple('NTUrl', ['id', 'raw', 'created_at'])):
    """ Url namedtuples, used as input when fetching html.

    Necessary fields are:
        `id`, to identify url in the database;
        `raw`, used as input for scrapy request;
        `created_at`, used as article.date_published.
    """
    pass


class NTArticle(namedtuple('NTArticle', ['id', 'canonical_url', 'site_id'])):
    """Article named tuples, used as input when parsing article.

    Necessary fields are:
        `id`, to identify article in the database;
        `canonical_url`, input for scrapy request, sepcifically, web parser
            service;
        `site_id`: used to generate `article.group_id`, combined with 'title'
            that is from web parser.
    """
    pass
